### ISSUE TITLE
Firmware URL wrong.

### ISSUE THREAD

**Issue by mischkasmith** [Homegear/Homegear-HomeMaticBidCoS#10]
The URLs for the firmware download not working anymore.  
Please change http to https in GetFirmwareUpdatesHomeMaticBidCoS.sh

--2018-11-03 18:06:59--  http://www.eq-3.de/Downloads/Software/Firmware/HM-ES-TX-WM_update_V1_2_160628.tgz
Auflösen des Hostnamens »www.eq-3.de (www.eq-3.de)« … 81.14.202.21
Verbindungsaufbau zu www.eq-3.de (www.eq-3.de)|81.14.202.21|:80 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2018-11-03 18:06:59 FEHLER 404: Not Found.

Complete install log: https://pastebin.com/W7sXyPtd

**Comment by hfedcba** [comment]
I changed all URLs to HTTPS. On my computer HTTP still works though for some reason.
