### ISSUE TITLE
Ubuntu Xenial upgrade HM-CFG-LAN: rfKey is not specified 0.7.34-2678 

### ISSUE THREAD

**Issue by linuxmail** [Homegear/Homegear-HomeMaticBidCoS#12]
Hello,

since the upgrade on Ubuntua Xenial from 0.7.30-1900 to 0.7.34-2678, my Homegear isn't working anymore with HM-CFG-LAN:

Module HomeMatic BidCoS: LAN-Konfigurationsadapter "LEQ0102548": Error: Cannot start listening , because rfKey is not specified.

rfKey is specified, I had to revert back to 0.7.30-1900 to get everything up and running again.

**Comment by hfedcba** [comment]
Could you post me a log of the startup process on loglevel 5?

**Comment by hfedcba** [comment]
Does your AES key consist of the letters 0 to 9 and A to F (or a to f) and is 32 letters long (i. e. is it a valid hexadecimal AES key)?

**Comment by linuxmail** [comment]
Hello, @hfedcba 

awesome ! the rfKey contained non HEX characters. After fixing it, it was working again :-)

Thanks.
