### ISSUE TITLE
Support RPI-RF-MOD

### ISSUE THREAD

**Issue by gdelmas** [Homegear/Homegear-HomeMaticBidCoS#14]
hey there,

are there plans to support the newer RPI-RF-MOD?

thanks

**Comment by hfedcba** [comment]
Hey,

we would need to sniff the communication first and it would only work for HomeMatic BidCoS and not for HomeMatic IP (the protocol has not been analyzed by anybody yet). It is some work. If somebody could analyze the UART communication I'll be happy to implement it.

Cheers,

Sathya

**Comment by gdelmas** [comment]
hey @hfedcba,

can you point me to some documentation about how to sniff the communication?

**Comment by hfedcba** [comment]
Hey @gdelmas,

the last time I sniffed the communication with a logic analyzer (Saleae Logic).

But it might be possible to use `strace` for example:

https://unix.stackexchange.com/questions/12359/how-can-i-monitor-serial-port-traffic

Cheers,

Sathya

**Comment by hfedcba** [comment]
Please use the homegear-ccu2 module.
