### ISSUE TITLE
Support multiple HM-MOD-RPI-PCB

### ISSUE THREAD

**Issue by mrRo8o7** [Homegear/Homegear-HomeMaticBidCoS#17]
It would be nice to support multiple HM-MOD-RPI-RCP, so that the module can be used as an additional physical interface. My goal is to extend the range of the signal to my garage with a second module in combination with ESP-LINK. At the moment I can configure several devices (deviceType = hm-mod-rpi-pcb), but only the (default = true) sends messages to the peers (as far as I can comprehend from the log). I think the peers should be mapped to its interface at peering time (via changing the default = true parameter before peering).

**Comment by hfedcba** [comment]
Good idea. Done. The interface was previously settable with `setInterface()`.

Thanks!
