### ISSUE TITLE
Peer HM-CC-RT-DN not updated immediately. No burst messages are sent.

### ISSUE THREAD

**Issue by mrRo8o7** [Homegear/Homegear-HomeMaticBidCoS#18]
My peer (HM-CC-RT-DN) is not updated immediately and the message is pending in the queue until the RT sends a wake-up, even though it is configured with BURST_RX = true (by default). I think this worked in a previous version of the module. Please correct me if this is not reproducible. Thank you.

**Comment by hfedcba** [comment]
The change is reverted. It should work as before in the next version.

**Comment by mrRo8o7** [comment]
Thanks for the fast response. 

Im still unable to set the temperature of HM_CC_RT_DN. Now the message is sent immediately, but the RT isnt responding. (Log: No answer to packet). My homegear settings are default. Pairing works without any problems. HM-TC-IT-WM-W-EU receives the temperature without a problem.

**Comment by mrRo8o7** [comment]
Looks like there is still a problem with burst messages. The RT reacts after holding the boost button for a few seconds. Again: My HM-TC-IT-WM-W-EU works like a charm (No problem with receiving).

**Comment by mrRo8o7** [comment]
Maybe it is a problem with pairing. The config is pending and the queue isnt cleared.

**Comment by hfedcba** [comment]
I just checked with the current nighly, it should work again (the stable should work as well). Could you send me a log excerpt of setting a value?
