### ISSUE TITLE
Links for Firmware are in some cases outdated - suggestion for script improvement

### ISSUE THREAD

**Issue by lhurt** [Homegear/Homegear-HomeMaticBidCoS#25]
The current firmware for HM-TC-IT-WM-W-EU is 1.4.

The script `GetFirmwareUpdatesHomeMaticBidCoS.sh` seems to be a bit bloated due to code duplication and it refers to hard coded versions, which is unevitable in some cases like HM-ES-TX-WM, HM-LC-Sw1PBU-FM and HM-SEN-RD-O.

All other firmwares could be downloaded by the script below with the most recent version. Please excuse that I didn't have the time to adjust it to be usable by Homegear. But it would be great it someone else could do it.

The beauty of it would be that it would always fetch the most recent version.

```
#!/bin/bash
output=`curl -s 'https://update.homematic.com/firmware/api/firmware/search/DEVICE' | sed s/'homematic.com.setDeviceFirmwareVersions('/''/ | sed s/');'/''/ |  jq -r '.[] | "\(.type)"'`

for row in ${output}; do
  curl -O -J -L  "https://ccu3-update.homematic.com/firmware/download?cmd=download&serial=0&product=${row}"
done
```

Thanks a lot

**Comment by hfedcba** [comment]
Nice, thanks! We don't have the time right now, to adjust the script as well. But if somebody would create a pull request with a working script, I'd be happy to merge it.

**Comment by hfedcba** [comment]
I merged it into `dev`, so it should be in the next nightly. Thank you!
