### ISSUE TITLE
Implement system test in module start including help how to fix issues

### ISSUE THREAD

**Issue by jwiesel** [Homegear/Homegear-HomeMaticBidCoS#9]
Hi there,
I've been trying to get homegear to work with my hardware module "HM-MOD-RPI-PCB" for some time now and faced a lot of problems not being able to use the hardware module.
System setup: Raspi 3, 16 GB SanDisk SD Class 10, OpenHABian setup via WiFi, Homegear installed from openhabian-conf tool, serial ports disabled via openhabian-conf tool.
Apparently a lot of other users face the same problem (just a few examples):
https://forum.homegear.eu/t/Homegear-no-response-received-to-packet-on-Raspi2-mit-HM-MOD-RPI-PCB/1073
https://forum.homegear.eu/t/hm-mod-rpi-pcb-und-homegear-error-no-response-received-to-packet/1656
https://forum.homegear.eu/t/HM-MOD-RPI-PCB-Raspi-3/1467
https://community.openhab.org/t/openhab2-homematic-on-1-raspberry-pi/23578/30
https://openhabforum.de/viewtopic.php?f=15&t=627

As the Homegear-HomeMaticBidCos module seems to have a lot of system dependencies, I'd like to suggest the following feature:
When starting the module, do a system test of all possible problems one by one and inform the user, if something is not setup correctly **and how to fix it**.
Example:
Checking firmware version of "HM-MOD-RPI-PCB".
Your firmware version 1.2.1 is not supported by homegear. Please update the firmware version to 2.0 or higher as described here: <link>"

After the problems I faced, the following checks would be helpful (maybe there are more):
* check firmware version of hardware-module
* check centralAddress in bidcos.conf
* check, if a bidcos device is configured correctly in bidcos.conf
* check, if bidcos device is accessible (serial port, GPIO pins, etc.)
* ...

**Comment by hfedcba** [comment]
I implemented global service messages just before my vacation, so it's possible now to show descriptive error messages. As the HM-MOD-RPI-PCB makes a lot of problems, those help messages make a lot of sense.
